# Generated by Django 6.0.7 on 2026-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('jummah', 'Jummah Khutbah'), ('eid', 'Eid Celebration'), ('lecture', 'Islamic Lecture'), ('nikah', 'Nikah Ceremony'), ('funeral', 'Funeral / Janazah'), ('fundraiser', 'Fundraiser'), ('ramadan', 'Ramadan Program'), ('class', 'Quran / Islamic Class'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('speaker', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(default='Main Hall', max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
