# Generated by Django 6.0.7 on 2026-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('fajr_adhan', models.TimeField()),
                ('fajr_iqamah', models.TimeField()),
                ('dhuhr_adhan', models.TimeField()),
                ('dhuhr_iqamah', models.TimeField()),
                ('asr_adhan', models.TimeField()),
                ('asr_iqamah', models.TimeField()),
                ('maghrib_adhan', models.TimeField()),
                ('maghrib_iqamah', models.TimeField()),
                ('isha_adhan', models.TimeField()),
                ('isha_iqamah', models.TimeField()),
                ('jummah_khutbah', models.TimeField(blank=True, null=True)),
                ('jummah_iqamah', models.TimeField(blank=True, null=True)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
